### Price & Discount Relationships

11. Is there a **significant difference** between the average **discounted price** and **actual price** across product categories?
    → (*t-test or ANOVA*)

12. Is there a **correlation** between **discount percentage** and **rating**?
    → (*Correlation analysis or regression*)

13. Do **higher discounts** lead to **higher customer ratings**?
    → (*Hypothesis testing: H₀ = no relationship*)

14. Does the **number of reviews (rating_count)** affect the **average rating**?
    → (*Correlation or regression*)

15. Is there a **significant difference** in average **ratings** between **top 3 product categories**?
    → (*ANOVA test*)

---

## what we are going to answer in that section

11. Is there a **significant difference** between the average **discounted price** and **actual price** across product categories?
    → (*t-test or ANOVA*)

In [1]:
import ast 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.ticker as mtick
import seaborn as sns
import statsmodels.api as sm


# Set the path to the file you'd like to load
file_path = 'M:/3_datasets/amazon_data.csv'

# Load the latest version
df = pd.read_csv(file_path)

# clean 
df['actual_price'] = (df['actual_price'].str.replace('₹', '', regex=False).str.replace(',', '', regex=False))
df['discounted_price'] = (df['discounted_price'].str.replace('₹', '', regex=False).str.replace(',', '', regex=False))
df['discount_percentage'] = (df['discount_percentage'].str.replace('%', '', regex=False).str.replace(',', '', regex=False))
df['rating_count'] = (df['rating_count'].str.replace(',', '', regex=False))
df['rating'] = (df['rating'].str.replace('|', '0', regex=False))


df['actual_price']= df['actual_price'].astype(float)
df['discounted_price']= df['discounted_price'].astype(float)
df['discount_percentage']= df['discount_percentage'].astype(float)
df['rating_count']= df['rating_count'].astype(float)
df['rating']= df['rating'].astype(float)

# turn discount_percentage to float percentage
df['discount_percentage']= df['discount_percentage'].apply(lambda x: x/100)

# make the discounted_price more accurate
df['discounted_price'] = (df['actual_price'] * (1 - df['discount_percentage']))

# Read before statring your next step


Perfect, Mina! Since you already know **Python basics**, the next step is learning **data analysis/statistical testing in Python**. Let’s break down each of your questions and what Python skills/libraries you need.

---

## **11. Difference between discounted price and actual price (t-test or ANOVA)**

* **Goal:** Test whether the average `discounted_price` is different from `actual_price` across categories.
* **Python skills needed:**

  1. **Data manipulation** → `pandas` (groupby, mean, filtering)
  2. **t-test / ANOVA** → `scipy.stats` or `statsmodels`

     ```python
     from scipy.stats import ttest_rel, f_oneway
     # Paired t-test if same products
     t_stat, p_val = ttest_rel(df['discounted_price'], df['actual_price'])
     # ANOVA if across categories
     f_stat, p_val = f_oneway(df_cat1['discounted_price'], df_cat2['discounted_price'], ...)
     ```
  3. **Data visualization (optional but helpful)** → `matplotlib` or `seaborn` for boxplots

✅ **Learn:** `pandas groupby`, `scipy.stats.ttest_rel`, `f_oneway`, `seaborn.boxplot`

---

## **12. Correlation between discount percentage and rating**

* **Goal:** See if `discount_percentage` and `rating` move together.
* **Python skills needed:**

  1. **Pearson/Spearman correlation** → `scipy.stats`

     ```python
     from scipy.stats import pearsonr, spearmanr
     corr, p_val = pearsonr(df['discount_percentage'], df['rating'])
     ```
  2. **Scatter plot** → visualize relationship

     ```python
     import seaborn as sns
     sns.scatterplot(x='discount_percentage', y='rating', data=df)
     ```
  3. (Optional) **Linear regression** → `statsmodels` for detailed modeling

     ```python
     import statsmodels.api as sm
     X = sm.add_constant(df['discount_percentage'])
     model = sm.OLS(df['rating'], X).fit()
     print(model.summary())
     ```

✅ **Learn:** `pearsonr`, `spearmanr`, scatter plots, simple OLS regression

---

## **13. Do higher discounts lead to higher ratings?**

* **Goal:** Test if discounts affect ratings → **hypothesis testing**
* **Python skills needed:**

  1. Categorize discounts (optional) → low/medium/high

     ```python
     df['discount_group'] = pd.cut(df['discount_percentage'], bins=[0,0.2,0.5,1.0], labels=['Low','Medium','High'])
     ```
  2. **ANOVA** → test if average rating differs by discount group

     ```python
     from scipy.stats import f_oneway
     f_stat, p_val = f_oneway(df[df['discount_group']=='Low']['rating'],
                              df[df['discount_group']=='Medium']['rating'],
                              df[df['discount_group']=='High']['rating'])
     ```
  3. **Visualization** → boxplots

     ```python
     sns.boxplot(x='discount_group', y='rating', data=df)
     ```

✅ **Learn:** `pd.cut`, ANOVA with `f_oneway`, boxplots

---

## **14. Does number of reviews (`rating_count`) affect average rating?**

* **Goal:** Check if products with more reviews have higher ratings.
* **Python skills needed:**

  1. **Correlation analysis** → `pearsonr` or `spearmanr`

     ```python
     corr, p_val = pearsonr(df['rating_count'], df['rating'])
     ```
  2. **Linear regression**

     ```python
     X = sm.add_constant(df['rating_count'])
     model = sm.OLS(df['rating'], X).fit()
     print(model.summary())
     ```
  3. **Visualization** → scatter + regression line

     ```python
     sns.regplot(x='rating_count', y='rating', data=df)
     ```

✅ **Learn:** correlation, OLS regression, scatter + regression plots

---

## **15. Difference in average ratings between top 3 categories**

* **Goal:** Compare average rating across 3 categories → **ANOVA**
* **Python skills needed:**

  1. Select **top 3 categories**

     ```python
     top3 = df['category_clean'].value_counts().nlargest(3).index
     df_top3 = df[df['category_clean'].isin(top3)]
     ```
  2. **One-way ANOVA**

     ```python
     f_stat, p_val = f_oneway(df_top3[df_top3['category_clean']==top3[0]]['rating'],
                              df_top3[df_top3['category_clean']==top3[1]]['rating'],
                              df_top3[df_top3['category_clean']==top3[2]]['rating'])
     ```
  3. **Boxplots**

     ```python
     sns.boxplot(x='category_clean', y='rating', data=df_top3)
     ```

✅ **Learn:** filtering in pandas, `value_counts()`, `f_oneway`, boxplots

---

## **Summary of Python skills to master**

| Task                         | Python skills / libraries                           |
| ---------------------------- | --------------------------------------------------- |
| t-test / ANOVA               | `scipy.stats.ttest_rel`, `f_oneway`                 |
| Correlation                  | `pearsonr`, `spearmanr`                             |
| Regression                   | `statsmodels.OLS`                                   |
| Data manipulation            | `pandas` (`groupby`, `cut`, `isin`, `value_counts`) |
| Visualization                | `matplotlib`, `seaborn` (scatter, boxplot, regplot) |
| Interaction terms (advanced) | `statsmodels.formula.api.ols`                       |

---

If you want, Mina, I can **make a roadmap for Python practice** specifically for **these 5 questions**, with small example codes so you can learn fast and practice on your dataset.

Do you want me to do that?


In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   product_id           1465 non-null   object 
 1   product_name         1465 non-null   object 
 2   category             1465 non-null   object 
 3   discounted_price     1465 non-null   float64
 4   actual_price         1465 non-null   float64
 5   discount_percentage  1465 non-null   float64
 6   rating               1465 non-null   float64
 7   rating_count         1463 non-null   float64
 8   about_product        1465 non-null   object 
 9   user_id              1465 non-null   object 
 10  user_name            1465 non-null   object 
 11  review_id            1465 non-null   object 
 12  review_title         1465 non-null   object 
 13  review_content       1465 non-null   object 
 14  img_link             1465 non-null   object 
 15  product_link         1465 non-null   o

In [3]:
df.head()

product_id                                       product_name  \
0  B07JW9H4J1  Wayona Nylon Braided USB to Lightning Fast Cha...   
1  B098NS6PVG  Ambrane Unbreakable 60W / 3A Fast Charging 1.5...   
2  B096MSW6CT  Sounce Fast Phone Charging Cable & Data Sync U...   
3  B08HDJ86NZ  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...   
4  B08CF3B7N1  Portronics Konnect L 1.2M Fast Charging 3A 8 P...   

                                            category  discounted_price  \
0  Computers&Accessories|Accessories&Peripherals|...            395.64   
1  Computers&Accessories|Accessories&Peripherals|...            198.93   
2  Computers&Accessories|Accessories&Peripherals|...            189.90   
3  Computers&Accessories|Accessories&Peripherals|...            328.53   
4  Computers&Accessories|Accessories&Peripherals|...            155.61   

   actual_price  discount_percentage  rating  rating_count  \
0        1099.0                 0.64     4.2       24269.0   
1         349.0                 0.43     4.0       43994.0   
2        1899.0                 0.90     3.9        7928.0   
3         699.0                 0.53     4.2       94363.0   
4         399.0                 0.61     4.2       16905.0   

                                       about_product  \
0  High Compatibility : Compatible With iPhone 12...   
1  Compatible with all Type C enabled devices, be...   
2  【 Fast Charger& Data Sync】-With built-in safet...   
3  The boAt Deuce USB 300 2 in 1 cable is compati...   
4  [CHARGE & SYNC FUNCTION]- This cable comes wit...   

                                             user_id  \
0  AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...   
1  AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...   
2  AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...   
3  AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...   
4  AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...   

                                           user_name  \
0  Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...   
1  ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...   
2  Kunal,Himanshu,viswanath,sai niharka,saqib mal...   
3  Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...   
4  rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...   

                                           review_id  \
0  R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...   
1  RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...   
2  R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...   
3  R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...   
4  R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...   

                                        review_title  \
0  Satisfied,Charging is really fast,Value for mo...   
1  A Good Braided Cable for Your Type C Device,Go...   
2  Good speed for earlier versions,Good Product,W...   
3  Good product,Good one,Nice,Really nice product...   
4  As good as original,Decent,Good one for second...   

                                      review_content  \
0  Looks durable Charging is fine tooNo complains...   
1  I ordered this cable to connect my phone to An...   
2  Not quite durable and sturdy,https://m.media-a...   
3  Good product,long wire,Charges good,Nice,I bou...   
4  Bought this instead of original apple, does th...   

                                            img_link  \
0  https://m.media-amazon.com/images/W/WEBP_40237...   
1  https://m.media-amazon.com/images/W/WEBP_40237...   
2  https://m.media-amazon.com/images/W/WEBP_40237...   
3  https://m.media-amazon.com/images/I/41V5FtEWPk...   
4  https://m.media-amazon.com/images/W/WEBP_40237...   

                                        product_link  
0  https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...  
1  https://www.amazon.in/Ambrane-Unbreakable-Char...  
2  https://www.amazon.in/Sounce-iPhone-Charging-C...  
3  https://www.amazon.in/Deuce-300-Resistant-Tang...  
4  https://www.amazon.in/Portronics-Konnect-POR-1...

### 11. Is there a **significant difference** between the average **discounted price** and **actual price** across product categories? → (*t-test or ANOVA*)

In [4]:
df['category_clean'] = df['category'].apply(lambda x: x.split('|')[-1])
df.sort_values(by= 'category')

product_id                                       product_name  \
1157  B0912WJ87V  Reffair AX30 [MAX] Portable Air Purifier for C...   
695   B097C564GC  rts [2 Pack] Mini USB C Type C Adapter Plug, T...   
742   B094DQWV9B  Kanget [2 Pack] Type C Female to USB A Male Ch...   
906   B009LJ2BXA  Hp Wired On Ear Headphones With Mic With 3.5 M...   
748   B08SCCG9D4  JBL Commercial CSLM20B Auxiliary Omnidirection...   
...          ...                                                ...   
858   B00LOD70SC  Pilot V7 Liquid Ink Roller Ball Pen (2 Blue + ...   
850   B07SBGFDX9     Pentonic Multicolor Ball Point Pen, Pack of 10   
919   B00LZPQVMK  Parker Vector Standard Chrome Trim Ball Pen (I...   
955   B0746N6WML  Parker Vector Camouflage Gift Set - Roller Bal...   
924   B00DJ5N9VK  Faber-Castell Connector Pen Set - Pack of 25 (...   

                                               category  discounted_price  \
1157  Car&Motorbike|CarAccessories|InteriorAccessori...           2320.00   
695   Computers&Accessories|Accessories&Peripherals|...            299.94   
742   Computers&Accessories|Accessories&Peripherals|...            147.63   
906   Computers&Accessories|Accessories&Peripherals|...            649.35   
748   Computers&Accessories|Accessories&Peripherals|...            940.00   
...                                                 ...               ...   
858   OfficeProducts|OfficePaperProducts|Paper|Stati...            178.50   
850   OfficeProducts|OfficePaperProducts|Paper|Stati...            120.00   
919   OfficeProducts|OfficePaperProducts|Paper|Stati...            272.00   
955   OfficeProducts|OfficePaperProducts|Paper|Stati...            342.00   
924   Toys&Games|Arts&Crafts|Drawing&PaintingSupplie...            150.00   

      actual_price  discount_percentage  rating  rating_count  \
1157        4000.0                 0.42     3.8        1118.0   
695         4999.0                 0.94     4.3        4426.0   
742          399.0                 0.63     4.0        1540.0   
906          999.0                 0.35     3.5        7222.0   
748         2000.0                 0.53     3.9       14969.0   
...            ...                  ...     ...           ...   
858          210.0                 0.15     4.3        2450.0   
850          120.0                 0.00     4.1        4308.0   
919          320.0                 0.15     4.0        3686.0   
955          450.0                 0.24     4.3        2493.0   
924          150.0                 0.00     4.3       15867.0   

                                          about_product  \
1157  [NEW LAUNCH - INNOVATIVE DESIGN] EFFICIENT PUR...   
695   【WIDER COMPATIBILITY】This USB C Female to USB ...   
742   👍【USB C TO USB ADAPTER】-This is a USB C FEMALE...   
906   Powerful bass and clear treble sounds|Wired co...   
748   Omnidirectional pickup pattern|3.5mm TRRS jack...   
...                                                 ...   
858   Unique 3 dimple tip technology from Japan for ...   
850   0.7 mm tip size|Black Body, Multicolor Ink(Bla...   
919   A solid plastic body of the glossy black desig...   
955   This charming looking pen is made up of ABS pl...   
924   Simply draw and color or clip these pens toget...   

                                                user_id  \
1157  AG6W5HESRSDLBX3NCYOOUGFOWERA,AED4U5CF37HVSYPMD...   
695   AGO5SRT3ESLNL5WTRQFD5BSIYPQA,AGGNODUMRADB3PQQT...   
742   AFA6YM4NTFRGHHKYN5U7HUYEVSUA,AEB3EVUTQCHIE3PGI...   
906   AFIZUD4UBB67LGWY6CVLRHKA75IA,AG2TD3527KNZZNE46...   
748   AFROXVCIF6PZXFXLS7DLTPT2CGCQ,AHA4ODJMDNBNUVEUS...   
...                                                 ...   
858   AG3G7G2DUJKN5YMCOYZNCADKKJUQ,AH44B2X6AT45J37MH...   
850   AGK76H5VGHDWFQD7JTHVKZNQ5BHA,AHWXK2FU23OBRZZUA...   
919   AE3S2ZAEMH765KUJ57DR6HBZBB3Q,AHSIVUNTJMI5S5AJG...   
955   AFVTO4K2IG5AYWZPOAEA2QGPZZ4A,AHWTCTHLUKPJP2IUI...   
924   AE5D3EMPETKIA4VU4SZU5UIHXKQA,AFF76KWKCMR6GNPUX...   

                             

In [5]:
# 1. Create price_diff for each product
df['price_diff'] = df['actual_price'] - df['discounted_price']

In [ ]:
# 2. Group by category (only include categories with >1 item)
groups = [] 

for category_name, group in df.groupby('category_clean'):
    if len(group) > 1:

        price_diff_values = group['price_diff'].values
        
        groups.append(price_diff_values)


[array([390.  , 879.12, 879.12]),
 array([ 4372.5 ,  2782.8 ,  2798.6 , 15036.75,  4178.1 ]),
 array([948.27, 832.51, 363.48, 948.27, 429.57]),
 array([1214.19, 1709.1 ,  987.62, 1331.26]),
 array([ 303.81,  303.81,  373.78,  373.78,  228.2 ,  228.2 ,  389.87,
        1483.72,  199.84]),
 array([ 749.25, 1405.26]),
 array([1241.46,  449.55,  989.67, 3193.6 ,  299.75, 2793.  ]),
 array([ 0., 10.]),
 array([899.1, 899.1, 899.1]),
 array([  0.  , 230.23,   0.  ]),
 array([ 987.74,  999.5 , 3999.6 , 2220.  ]),
 array([ 379.24,  944.37, 1949.22]),
 array([1093.4 , 1608.9 ,  988.9 , 1250.2 ,  892.62, 2769.5 ,  571.2 ,
         895.5 , 1121.4 , 2198.8 ,  852.6 ]),
 array([ 63.  ,  55.8 , 158.4 ,   8.25,   0.  ,   0.  ,   0.  ]),
 array([1197.  ,  223.68]),
 array([999.5, 399.6]),
 array([ 649.35, 1519.24,  399.6 ]),
 array([1799.1 ,  204.59, 1199.4 ,  797.58,  189.62, 2211.21, 2189.27,
         305.49, 1239.38,   11.67]),
 array([705.,   0.]),
 array([ 50.4 ,  30.6 ,  47.25,  21.6 ,  30.8 , 2